services:
  llama:
    build: .
    ports:
      - "8081:8080"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - default
      - llm

networks:
  llm:
    external: true
